// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenWindowsPatchMan.ConsoleAgent;

#nullable disable

namespace OpenWindowsPatchMan.ConsoleAgent.Migrations
{
    [DbContext(typeof(UpdateContext))]
    [Migration("20240810112249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("OpenWindowsPatchMan.ConsoleAgent.WindowsUpdateInfo", b =>
                {
                    b.Property<int>("WindowsUpdateInfoEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BundledUpdates")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Categories")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DatePublished")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeploymentAction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("DownloadSizeMB")
                        .HasColumnType("REAL");

                    b.Property<string>("InstallationRebootBehavior")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBeta")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDownloaded")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInstalled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUninstallable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KBArticleIDs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoreInfoUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SecurityBulletinIDs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupersededUpdateIDs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SupportUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UninstallationNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UninstallationRebootBehavior")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UninstallationSteps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdateCheckTime")
                        .HasColumnType("TEXT");

                    b.HasKey("WindowsUpdateInfoEntryId");

                    b.ToTable("WindowsUpdateInfo", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
